### ISSUE TITLE
*TODO* Clean up the code. Do some optimizations

### ISSUE THREAD

**Issue by TRSGuy** [TRSGuy/Improved-Novaschem#1]
Comment on the code, make it easier to read. Make variables for commonly used elements and make functions for things that both mobile and Desktop/tablet javascript do. Re-structure the whole code.

- [x] Fix all javascript errors
- [x] Restructure the code
- [x] Comment on it
- [x] Get mobile width to work

**Comment by TRSGuy** [comment]
Will do this tomorrow. Will also pull development branch into master

**Comment by TRSGuy** [comment]
Just started working on this. Commited to the dev branch. Started spacing out and structure the javascript  and fixed some issues. Still having problems pulling the dimensions of the screen in render_mobile(). Will try to fix this and finish the dev branch for pulling

**Comment by TRSGuy** [comment]
Feature Request: Make an outline around the current day on mobile.

**Comment by TRSGuy** [comment]
All of this is finally done :D
